server:
  port: 8080
spring:
  application:
    name: sellergoods-service
  resources:
    static-locations: classpath:/static
  mvc:
    view:
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.52.67:3306/BcryptExample?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis:
  type-aliases-package: com.someexp.model
  mapper-locations: classpath:mapper/*